# See https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/example.yml
server:
  applicationConnectors:
    - type: http
      port: 8095
  adminConnectors:
    - type: http
      port: 8096


# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  # the username
  user: postgres
  # the password
  password: welcome1
  # the JDBC URL
  url: jdbc:postgresql://localhost/hierarchy_db
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect